[nixpkgs]
archive = "ed67bc86e84e51d4a88e73c7fd36006dc876476f"

[phases.setup]
nixPkgs = ["jdk17", "nodejs_22", "maven"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd backend && mvn package -DskipTests"
]

[start]
cmd = "java -jar backend/target/backend-0.0.1-SNAPSHOT.jar"
