[nixpkgs]
archive = "50ab793786d9de88ee30ec4e4c24fb4236fc2674"

[phases.setup]
nixPkgs = ["jdk17", "nodejs_22", "maven"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd backend && mvn package -DskipTests"
]

[start]
cmd = "java -jar backend/target/backend-0.0.1-SNAPSHOT.jar"
